#
# Module manifest for module 'tcs.confluence'
#
# Generated by: Nigel Tatschner
#
# Generated on: 17/01/2025
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.0.31'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '8e75db44-4f93-4ab4-b151-06ec760efb21'

# Author of this module
Author = 'Nigel Tatschner'

# Company or vendor of this module
CompanyName = 'Rothesay'

# Copyright statement for this module
Copyright = '(c) 2025 Nigel Tatschner. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Functions to work with Confluence documents'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('rsy.core')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('tcs.confluence.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'ConvertTo-ConfluenceHTML',
    'Get-ConfluencePage',
    'Get-ConfluencePageContent',
    'Get-ConfluenceSpaces',
    'Get-HtmlTableRowData',
    'Invoke-ConfluenceRequest',
    'Join-ConfluenceContent',
    'New-ConfluenceContentCodeBlock',
    'New-ConfluenceContentDivider',
    'New-ConfluenceContentHeader',
    'New-ConfluenceContentInfo',
    'New-ConfluenceContentInternalLink',
    'New-ConfluenceContentLink',
    'New-ConfluenceContentTable',
    'New-ConfluenceContentTOC',
    'New-ConfluencePage',
    'New-ConfluencePageLayout',
    'New-HtmlTable',
    'Remove-DuplicateConfluencePages',
    'Set-ConfluenceContext',
    'Update-ConfluencePage'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("Confluence", "Atlassian", "Documentation", "Wiki", "REST API")

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
0.0.30 - 2025-08-13
- Fixed critical syntax errors (mismatched braces) in Remove-DuplicateConfluencePages that prevented module import
- Simplified sorting logic and corrected ShouldProcess handling in Remove-DuplicateConfluencePages

0.0.29 - 2025-08-13
- Fixed syntax/bracing errors in Remove-DuplicateConfluencePages (module import failure)
- Ensured safe colon interpolation in Set-ConfluenceContext

0.0.28 - 2025-08-13
- Fixed variable interpolation issues with colon in Set-ConfluenceContext (added braces)
- Corrected warning message formatting in Remove-DuplicateConfluencePages to avoid invalid variable reference

0.0.27 - 2025-08-13
- Fixed Set-ConfluenceContext auth header creation (removed -f formatting to avoid brace-related FormatException)

0.0.26 - 2025-08-13
- Added legacy path & full URL parsing support in Invoke-ConfluenceRequest
- Refactored Get-ConfluencePageContent, Get-ConfluenceSpaces, Get-ConfluencePage, Update-ConfluencePage, Remove-DuplicateConfluencePages to use Invoke-ConfluenceRequest
- Enhanced Set-ConfluenceContext normalization (API suffix stripping, token masking)
- Unified pagination, query handling and deletion via wrapper

0.0.25 - 2025-08-13
- Refactored Get-ConfluenceSpaces to use Invoke-ConfluenceRequest (-Resource spaces) with built-in pagination
- Added new Get-ConfluencePageContent implementation using Invoke-ConfluenceRequest (-Resource pages / -Search)
- Updated Update-ConfluencePage to use PUT via Invoke-ConfluenceRequest (-Resource pages -Id)
- Updated Remove-DuplicateConfluencePages to delete via Invoke-ConfluenceRequest (DELETE pages/{id})
- Simplified Get-ConfluencePage to rely on -Resource pages abstraction
- Enhanced Set-ConfluenceContext: normalizes base URL, strips API suffix, masks stored token
- Added legacy path/token support and full URL parsing inside Invoke-ConfluenceRequest
0.0.24 - 2025-08-13
- Fixed intermittent loss of base URL during query assembly in Invoke-ConfluenceRequest
- Replaced interpolated endpoint construction with deterministic base + query concatenation
- Added repair safeguard if endpoint lacks scheme after build

0.0.23 - 2025-08-13
- Fixed endpoint construction losing base URL (query-only URI) in Invoke-ConfluenceRequest
- Introduced EndpointBase + deterministic assembly after query building
- Added scheme/malformed endpoint guard and richer validation diagnostics

0.0.22 - 2025-08-13
- Fixed loss of base URL when appending query parameters in Invoke-ConfluenceRequest
- Added reconstruction safeguard if Endpoint becomes empty prior to query assembly
- Trimmed API suffix from ConnectionURI and normalized base to prevent duplication
- Treated numeric spaceKey input as spaceId automatically (v2 pages)
- Added additional endpoint validation and verbose output

0.0.21 - 2025-08-13
- Added robust base and final endpoint URI validation (TryCreate) to prevent "hostname could not be parsed" errors
- Implemented additional normalization: duplicate scheme removal, whitespace stripping, query/fragment stripping
- Added final endpoint validity check with detailed error context

0.0.20 - 2025-08-13
- Fixed duplicated API path construction when ConnectionURI already includes /wiki/api/v2 or /wiki/rest/api and a full path was passed
- Added normalization to strip redundant API segments and regex collapse safeguard

0.0.19 - 2025-08-13
- Added high-level -Resource / -ApiVersion / -Id / -RawPath parameters to Invoke-ConfluenceRequest for smart endpoint construction
- URIPath now optional when using -Resource; retains backward compatibility
- Wildcard v2->v1 fallback and spaceKey->spaceId resolution preserved

0.0.18 - 2025-08-13
- Added -Resource, -ApiVersion, -Id, -RawPath parameters to Invoke-ConfluenceRequest for higher-level endpoint construction
- URIPath now optional when using -Resource; preserves backward compatibility
- Automatic v2->v1 fallback & spaceKey resolution still applied when appropriate

0.0.17 - 2025-08-13
- Moved API version selection, wildcard search fallback (v2->v1), and spaceKey->spaceId resolution into Invoke-ConfluenceRequest
- Simplified Get-ConfluencePage to a thin wrapper over v2 pages endpoint
- Added automatic endpoint switching for wildcard searches and enhanced verbose output

0.0.16 - 2025-08-13
- Added detailed verbose logging to Invoke-ConfluenceRequest (URI normalization, query params, pagination
- Updated Get-ConfluencePage to use Confluence Cloud endpoints and conditional CQL search
- Improved robustness of request building to prevent hostname parse errors

0.0.12 - 2025-08-08
- Enhanced error handling in New-ConfluencePage to better handle API inconsistencies
- Added multiple fallback mechanisms for page retrieval when API reports errors
- Improved page conflict detection and resolution
- Added additional checks to handle cases where pages are created but API reports failure

0.0.11 - 2025-08-08
- Added new function Remove-DuplicateConfluencePages to find and remove duplicate pages
- Function supports keeping either newest or oldest version of duplicate pages
- Added proper error handling and verbose logging
- Returns the kept page for further processing

0.0.10 - 2025-08-08
- Replaced page creation strategy to prioritize updating existing pages
- Improved page search to find pages with similar titles under the same parent
- Added fallback to update any page under the same parent when exact matches aren't found
- Removed unique title generation to prevent duplicate pages
- Always attempts to use original title to maintain consistency

0.0.9 - 2025-08-08
- Completely redesigned page conflict handling in New-ConfluencePage
- Added broader search capability to find conflicting pages
- Implemented a unique title strategy that doesn't require subsequent updates
- Enhanced error handling for Confluence API limitations

0.0.8 - 2025-08-08
- Added workaround for "Page already exists" errors when the page can't actually be found
- Implemented a temporary title strategy for creating new pages when Confluence reports a conflict
- Added more detailed verbose logging for page creation/update operations

0.0.7 - 2025-08-08
- Fixed issue in New-ConfluencePage function when updating existing pages
- Improved error handling with more detailed error messages
- Added robust response parsing to handle different API response structures
- Enhanced logging with verbose output for better troubleshooting
- Fixed issues with page ID extraction in various functions

0.0.6 - Previous version
- Added the Get-ConfluencePageContent function.
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
